version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: nest_app

    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - mysql
      - redis

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: nest_db

      REDIS_HOST: redis
      REDIS_PORT: 6379

  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_db
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_cache_2
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  mysql_data: