services:
  mysql:
    container_name: monshim_mysql_dev
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_db

  redis:
    container_name: monshim_redis_dev
    ports:
      - "6381:6379"

  backend:
    container_name: monshim_backend_dev

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: nest_db

      REDIS_HOST: redis
      REDIS_PORT: 6379

      NODE_ENV: development
      PORT: 3000

      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"

    volumes:
      - .:/backend
      - /backend/node_modules