FROM node:22-alpine

WORKDIR /backend

RUN corepack disable

RUN npm install -g pnpm@8.15.4

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "start:dev"]